/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.yit;

import org.junit.Test
import org.junit.Assert.assertEquals
class MainTest {
@Test
fun testAddNumbers() {
val num1 = 10.0
val num2 = 5.0

val result = addNumbers(num1, num2)
assertEquals(
"The sum of $num1 and $num2 should be 15.0",
15.0,
result,
0.001
)
}
}