/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.yit;

fun addNumbers(num1: Double, num2: Double): Double { // ← Top-level
return num1 + num2
}

fun main() {
val num1 = 10.0
val num2 = 5.0
val result = addNumbers(num1, num2) // Can call from anywhere
println("The sum of $num1 and $num2 is: $result")
}